### ISSUE TITLE
Edge shouldn't throw error if the player can't move in a direction

### ISSUE THREAD

**Issue by TrangPham** [DPenner/SYSC-Project#10]
Stops the game completely if player enters a bad direction string

**Comment by DPenner** [comment]
I thought the parser guaranteed the string would be good? And I'm not quite sure which exception you're talking about, but I did remove one from the getOtherTile() method...It was old code, just kept forgetting to remove it, but its done now.

**Comment by TrangPham** [comment]
FIXED: bad string outputs an error because I caught the exception in Game class

NEEDS FIXING:

Exception thrown when have added an edge with one null tile (boundary of map). From the look command the edge "south" references a null tile because it is a boundary. If you want it to throw an exception then throw "Boundary of map" else just make canMove return false.

Welcome to the World of Zuul!
World of Zuul is a new, incredibly boring adventure game.
Type 'help' if you need help.

> look
> north: There is a wall.
> east: There is a wall.
> south: Can move south. No character in front of you.
> west: There is a wall.
> go south
> You have moved south
> look
> north: Can move north. No character in front of you.
> Exception in thread "main" java.lang.IllegalArgumentException: Edge does not exist in that direction
>     at gameCore.Tile.getEdge(Tile.java:114)
>     at gameCore.Tile.canCrossEdge(Tile.java:198)
>     at gameCore.Tile.canMove(Tile.java:208)
>     at gameCore.Player.look(Player.java:124)
>     at gameLoader.Game.look(Game.java:351)
>     at gameLoader.Game.processCommand(Game.java:11)
>     at gameLoader.Game.play(Game.java:63)
>     at gameLoader.Game.main(Game.java:380)
> east: Can move east. No character in front of you.
