### ISSUE TITLE
Look command

### ISSUE THREAD

**Issue by DPenner** [DPenner/SYSC-Project#4]
Hello, how do you want the look command to work? I assume maybe one method called look(direction), but what would be the return value? Or maybe multiple methods like lookForCharacter(direction), lookForItems(direction). What if there's an uncrossable Edge in the way (like a wall or locked exit)?

**Comment by TrangPham** [comment]
Yes do lookforcharacter and lookforitem and do look itself. Return null if
nothing is there. Then in game I will call those

**Comment by TrangPham** [comment]
I mean in game it will have method look which calls lookforcharacter
lookforitem. Those return null if edge not crossable or null if no
character/item found

**Comment by DPenner** [comment]
Okay sounds good. Those methods though have been shipped off to the Character class though. Karen and I talked a little before yesterday's economics class and we both had come to the conclusion that having the Tile handle everything for the character was a bad idea...especially since the drop item looked like the Game telling the Tile to tell the Character to drop an item...so now, the Game class really only needs a reference to the Character and not the Tile.
