### ISSUE TITLE
This sub directory structure is causing problems with the git client and Eclipse

### ISSUE THREAD

**Issue by KMadore** [DPenner/SYSC-Project#6]
Any chance you could move the whole project right into the main sysc-project folder?

Thanks,

Karen

**Comment by DPenner** [comment]
I'm not quite sure how to do that...Are you sure it's the directory structure? The structure appears to work fine on mine and Trang's machines.

**Comment by KMadore** [comment]
I am still too new to know for certain.  Alex seems to think this is causing part of my problems.  I also created a new branch and still see some of the same problems appearing.  In particular, it is not able to resolve pretty much every class now.  

---Wait a second - I made just made a small change change in my preferences - JAVA - installed JREs and it seems to be helping.  --- Interesting since I have not modified my preferences for Eclipse since I had it set up and running over a year ago.  Anyway, I am off an running for now...
